name: Agile_Upgrade

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/ChangeLog.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/ChangeLog.md'

jobs:
  example-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # If your document requires Git submodules, uncomment the next line
          # submodules: true

      - name: Install Tools
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install cmake

      - name: Example Compile
        shell: bash
        run: |
          cd example
          cmake -B build
          cmake --build build
          cd build && ctest
